### ISSUE TITLE
Is there any update about ipmbbridge?

### ISSUE THREAD

**Issue by warp5tw** [openbmc/ipmbbridge#1]
Hi:

May I know the progress of the ipmbbridge project? Any reference code?

Thank you.

**Comment by edtanous** [comment]
A review for the latest implementation is in progress here:
https://gerrit.openbmc-project.xyz/#/c/openbmc/ipmbbridge/+/11130/

We haven't gotten very many code review comments on it, so merging it has been slow, as we seem to be the only ones that needed it.  It would be great if you could log into gerrit and review it.

**Comment by warp5tw** [comment]
Hi:

Just did a quick code review. 

Thank you.
