### ISSUE TITLE
ipmbbridge uses deprecated i2ctools headers

### ISSUE THREAD

**Issue by feistjj** [openbmc/ipmbbridge#4]
Details can be found here: https://lists.ozlabs.org/pipermail/openbmc/2019-January/014911.html

**Comment by feistjj** [comment]
@dfrycki was looking into this issue.

**Comment by williamspatrick** [comment]
@edtanous - Any idea what deprecated header this was in reference to?  It doesn't seem like `i2c/smbus.h` is actually deprecated to me.

**Comment by williamspatrick** [comment]
I think this was fixed with a8c77dc857fdf7fc049b975c3b3a6be11e7ea4c0 which incorrectly said "closes #3".
