### ISSUE TITLE
Ipmb channel not working

### ISSUE THREAD

**Issue by HCLOpenBMC** [openbmc/ipmbbridge#5]
Hi All,

    Ipmb channel communication is not working after the below commit id change.
    15185ff6c73e35281c6924d820ca680658e980a0.

    In our system, Ipmb channel communication was working before to communicate with host to get the details.
    Now, it is breaking the ipmb channel communication.  

    After revoked the above commit changes, it is working fine as like earlier. 

    Could you please check this.

Thanks,
Kumar.

**Comment by williamspatrick** [comment]
I suspect this was fixed with 3e07b9ea353b794f9ef666172265ecc056e5cd4d.
