### ISSUE TITLE
explaination

### ISSUE THREAD

**Issue by YungeG** [openbmc/ipmbbridge#7]
I'm studying the code of *ipmbbridge* , since there is no docs explaining what ipmbbridge is , if there is anyone here who can help me what ipmbbridge does in openbmc ? 
I have leart a little IPMI specification , does the ipmbbridge corresponding to IPMB in  IPMI specification ?

**Comment by bjwyman** [comment]
I believe they correspond with each other.

Try searching the mailing list? https://lore.kernel.org/openbmc/?q=ipmbbridge

https://en.wikipedia.org/wiki/Intelligent_Platform_Management_Interface
https://en.wikipedia.org/wiki/Intelligent_Platform_Management_Interface#IPMI_components
"The satellite controllers within the same chassis connect to the BMC via the system interface called Intelligent Platform Management Bus/Bridge (IPMB) – an enhanced implementation of I²C (Inter-Integrated Circuit)."
